server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Study\native-file-repo
        git:
          uri: https://github.com/L-Woo/spring-cloud-config
#          username: [your username]
#          password: [your password]
#          uri: file://C:/Study/git-local-repo

